### ISSUE TITLE
UT servers not listed

### ISSUE THREAD

**Issue by SeriousBuggie** [chc/openspy-web-backend#1]
Reproduce:
1. Open http://beta.openspy.net/en/server-list/ut

Expected result: Appear server list.
Actual result: No servers here. It keep say `Loading server list... Please wait`, but nothing appear.

![img](https://github.com/chc/openspy-web-backend/assets/70026933/c515159b-ef1b-4195-a4dd-b079593ad545)

Sometimes servers appear. but usually no.

After while in console appear message about failed do request.
It try do http://beta.openspy.net/api/servers/ut, and get result 504 error.
![img](https://github.com/chc/openspy-web-backend/assets/70026933/4d8aa6a6-f6be-49de-b7dd-27cbc841fb65)
In console appear error:
![img](https://github.com/chc/openspy-web-backend/assets/70026933/5ed8f78a-b513-4e63-a7c0-160145a36882)
Call stack for this request:
![img](https://github.com/chc/openspy-web-backend/assets/70026933/7106550f-88cc-48e0-90c7-a0ad371fce23)

**Comment by chc** [comment]
This issue has been resolved, though more work will be needed on the website in the future, there should not be such performance issues anymore.

**Comment by SeriousBuggie** [comment]
It not show 504 now, but however it still lags as hells, and firefox not switch to other tab, until page not load. Which goes for few seconds.

I guess this related for show SVG as objects instead of show it as images.
